backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "01_About"
    label: "About"
    folder: "content/01_About"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "02_Contact"
    label: "Contact"
    folder: "content/02_Contact"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "03_School_Song"
    label: "School song"
    folder: "content/03_School_Song"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "04_Annual_Report"
    label: "Annual report"
    folder: "content/04_Annual_Report"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "04_Book_Lists"
    label: "Book lists"
    folder: "content/04_Book_Lists"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "01_management_committee"
    label: "Management committee"
    folder: "content/board/01_management_committee"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "admission-process"
    label: "Admission process"
    folder: "content/board/admission-process"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "enrollment"
    label: "Enrollment"
    folder: "content/board/enrollment"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "facilities"
    label: "Facilities"
    folder: "content/board/facilities"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "fee-structure"
    label: "Fee structure"
    folder: "content/board/fee-structure"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "staff-particulars"
    label: "Staff particulars"
    folder: "content/board/staff-particulars"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "transfer-certificate"
    label: "Transfer certificate"
    folder: "content/board/transfer-certificate"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "mandatory-public-disclosure"
    label: "Mandatory Public Disclosure"
    folder: "content/05_Mandatory_public_disclosure/01_mandatory_public_disclosure"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "details-of-curriculum"
    label: "Details of Curriculum"
    folder: "content/05_Mandatory_public_disclosure/02_details_of_curriculum"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "management-committee"
    label: "Management Committee"
    folder: "content/05_Mandatory_public_disclosure/03_management_committee"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "school-leaving-certificate"
    label: "School Leaving Certificate"
    folder: "content/05_Mandatory_public_disclosure/04_school_leaving_certificate"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "fee-structure"
    label: "Fee Structure"
    folder: "content/05_Mandatory_public_disclosure/05_fee_structure"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "fees-norms"
    label: "Fee Norms"
    folder: "content/05_Mandatory_public_disclosure/06_fees_norms"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "self-affidavit"
    label: "Self Affidavit"
    folder: "content/05_Mandatory_public_disclosure/07_self_affidavit"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "infrastructure-and-facilities"
    label: "Infrastructure and Facilities"
    folder: "content/05_Mandatory_public_disclosure/08_infrastructure_and_facilities"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "results-2021-22"
    label: "Results 2021-22"
    folder: "content/05_Mandatory_public_disclosure/09_results_2021-22"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "admission-form"
    label: "Admission Form"
    folder: "content/05_Mandatory_public_disclosure/10_admission_form"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "awards-and-recognition"
    label: "Awards and Recognition"
    folder: "content/05_Mandatory_public_disclosure/11_awards_and_recognition"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
