backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "01_About"
    label: "01_About"
    folder: "content/01_About"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "02_Contact"
    label: "02_Contact"
    folder: "content/02_Contact"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "03_School_Song"
    label: "03_School_Song"
    folder: "content/03_School_Song"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "04_Annual_Report"
    label: "04_Annual_Report"
    folder: "content/04_Annual_Report"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "04_Book_Lists"
    label: "04_Book_Lists"
    folder: "content/04_Book_Lists"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "01_management_committee"
    label: "01_management_committee"
    folder: "content/board/01_management_committee"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "admission-process"
    label: "admission-process"
    folder: "content/board/admission-process"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "enrollment"
    label: "enrollment"
    folder: "content/board/enrollment"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "facilities"
    label: "facilities"
    folder: "content/board/facilities"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "fee-structure"
    label: "fee-structure"
    folder: "content/board/fee-structure"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "staff-particulars"
    label: "staff-particulars"
    folder: "content/board/staff-particulars"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "transfer-certificate"
    label: "transfer-certificate"
    folder: "content/board/transfer-certificate"
    create: true
    editor:
     preview: false
    fields:
      - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      